### ISSUE TITLE
작성된 섹션 및 새로운 섹션 추가 기능

### ISSUE THREAD

**Issue by yonghyun421** [Readme-Monster/readme-monster#35]
<div type='discussions-op-text'>

<sup>Originally posted by **lee-ji-hong** April 18, 2024</sup>
작성된 섹션 및 새로운 섹션 추가 기능</div>

**Comment by lee-ji-hong** [comment]
- [ ] 추가된 섹션을 삭제하면 마크다운에서도 삭제된다.

**Comment by yonghyun421** [comment]
- [ ] 섹션 추가시 선택할수 있는 옵션 (있다면)
