### ISSUE TITLE
로그인 기능

### ISSUE THREAD

**Issue by yonghyun421** [Readme-Monster/readme-monster#36]
### Discussed in https://github.com/lee-ji-hong/readme-monster/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **yonghyun421** April 18, 2024</sup>
로그인 기능</div>

**Comment by lee-ji-hong** [comment]
- [ ] 유효성 검사

**Comment by yonghyun421** [comment]
- [ ] 중복체크
- [ ] id, pw
- [ ] email 인증(?)
