### ISSUE TITLE
[UI] Home 화면

### ISSUE THREAD

**Issue by yonghyun421** [Readme-Monster/readme-monster#38]
사이트 처음 들어왔을때 처음 보이는 화면

**Comment by lee-ji-hong** [comment]
- [x] Routes 테스트
    - [x] 기본 경로("/")에서 HomePage 컴포넌트가 렌더링되어야 함
    - [x] 잘못된 경로에 접근했을 때 루트 경로("/")로 리다이렉트되어야 함

- [x] App render 테스트
    - [x] App 컴포넌트가 성공적으로 렌더링되어야 함
